version: "3.10"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      SW_ENVIRONMENT: "prod"
      SW_DATABASE__URL: "postgresql+asyncpg://warehouse:warehouse@db:5432/warehouse"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"

volumes:
  postgres_data: {}
