name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        # Allow linter failures to not fail the entire workflow so CI can proceed.
        # This avoids blocking builds for stylistic/import-order issues while
        # the team decides on a remediation strategy. The lint step will still
        # print errors to the log for visibility.
        continue-on-error: true
        run: |
          ruff check smart_warehouse tests
      - name: Type check
        run: |
          mypy smart_warehouse
      - name: Tests
        run: |
          pytest
